git lfs track "*.bmp"
git lfs track "*.BMP"
git lfs track "*.jpg"
git lfs track "*.JPG"
git lfs track "*.png"
git lfs track "*.PNG"
git lfs track "*.lib"
git lfs track "*.zip"
git lfs track "*.ZIP"
git lfs track "*.obj"
git lfs track "*.pdb"
git lfs track "*.PDB"
git lfs track "*.a"
git add .gitattributes
